spring:
  datasource:
    url: jdbc:postgresql://ep-red-bread-a10aygvz-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_aG1O4KCMQfic
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kakao:
  rest-api-key: 'KakaoAK 99016e06b011e42fe7d6cad05167338d'